{% set name = "supervisor" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c479c875853e9c013d1fa73e529fd2165ff1ecaecc7e82810ba57e7362ae984d

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - gettext
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  requires:
    - pytest >=2.5.2
    - mock >=0.5.0
  source_files:
    - supervisor/tests/
  commands:
    - py.test supervisor/tests/
    - supervisord -h
    - supervisorctl -h
    - echo_supervisord_conf -h
  imports:
    - supervisor

about:
  home: http://supervisord.org/
  license: BSD-derived
  license_file: LICENSES.txt
  license_family: BSD
  summary: A Process Control System
  description: |
    Supervisor is a client/server system that allows its users to monitor and
    control a number of processes on UNIX-like operating systems.
  doc_url: http://supervisord.org/
  doc_source_url: https://github.com/Supervisor/supervisor
  dev_url: https://github.com/Supervisor/supervisor

extra:
  recipe-maintainers:
    - kalefranz
    - sodre
