{% set name = "supervisor" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9644990d21a1ba03b1a7ac5e9a0c0c62e12822e258f9e98f4a0b128461b3f10a

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - gettext
    - python
    - setuptools

  run:
    - python
    - meld3 >=1

test:
  requires:
    - pytest >=2.5.2
    - mock >=0.5.0
  source_files:
    - supervisor/tests/
  commands:
    - py.test supervisor/tests/
    - supervisord -h
    - supervisorctl -h
    - echo_supervisord_conf -h
  imports:
    - supervisor

about:
  home: http://supervisord.org/
  license: BSD-derived
  license_file: LICENSES.txt
  license_family: BSD
  summary: A Process Control System
  description: |
    Supervisor is a client/server system that allows its users to monitor and
    control a number of processes on UNIX-like operating systems.
  doc_url: http://supervisord.org/
  doc_source_url: https://github.com/Supervisor/supervisor
  dev_url: https://github.com/Supervisor/supervisor

extra:
  recipe-maintainers:
    - kalefranz
    - sodre
