{% set name = "supervisor" %}
{% set version = "4.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34761bae1a23c58192281a5115fb07fbf22c9b0133c08166beffc70fed3ebc12

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  requires:
    - pytest >=2.5.2
    - mock >=0.5.0
    - pip
  source_files:
    - supervisor/tests/
  commands:
    - cp -r supervisor/tests $SP_DIR/supervisor
    - py.test supervisor/tests
    - supervisord -h
    - supervisorctl -h
    - echo_supervisord_conf -h
    - pip check
  imports:
    - supervisor

about:
  home: http://supervisord.org/
  license: BSD-3-Clause-Modification AND BSD-3-Clause AND PSF-2.0
  license_file: LICENSES.txt
  summary: A Process Control System
  description: |
    Supervisor is a client/server system that allows its users to monitor and
    control a number of processes on UNIX-like operating systems.
  doc_url: http://supervisord.org/
  doc_source_url: https://github.com/Supervisor/supervisor
  dev_url: https://github.com/Supervisor/supervisor

extra:
  recipe-maintainers:
    - kalefranz
    - sodre
    - xhochy
